### ISSUE TITLE
Employee Number field not visible on login screen

### ISSUE THREAD

**Issue by oevans** [codylawson/etc-skin#1]
Love the idea! However, I observed this issue on Chrome/Mac OS 10.11.5 that makes the skin unusable since I can't log in. Once the CSS is applied the Employee Number field isn't visible on then login screen.

![2016-05-31 at 10 54 09 am](https://cloud.githubusercontent.com/assets/3215530/15678965/21097a7e-271e-11e6-8d02-06b921213f52.JPG)

**Comment by codylawson** [comment]
@oevans This is caused when you use the wrong url in stylebot, you have to use the full `http://www.selfservice/etc/cfdocs/detail` when using this skin. The skin was designed with only the detail page in mind and any other page may have unintended bugs.
